const Rows = (name) => {
  const arr = [
    {value: name},
    {value: '[agency]'},
    {value: '[catalog]'},
    {value: '[cat_no]'},
    {value: '[unit]'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'},
    {value: '0'}
  ];

  return arr;
} 

const SheetForm = [
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ],
  [
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null},
    {value: null}
  ]
];

const TitleLabel = [
  '입력자',
  '대리점',
  'Catalog',
  'cat no',
  'unit',
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec'
];

export {Rows, SheetForm, TitleLabel};